### ISSUE TITLE
Reading from xml not working

### ISSUE THREAD

**Issue by kriskhoury** [WelcomWeb/localizablejs#2]
Hey @WelcomWeb. Thanks for this little gem. Exactly what I needed!

I noticed an issue though. In order for me to loading a dictionary from xml read working, I had to place empty language objects in a dictionary object just before calling the read function. 
I placed the read right below my import:

```
import React from 'react';
import LocalizableJs from 'localizablejs';

var dictionaries = {
    "en-US": {},
    "sv-SE": {}
};
LocalizableJs.read('translations/dictionaries.xml','en-US');
LocalizableJs.init(dictionaries, "en-US");
```

This is my xml file (nothing much in there so far)

```
<?xml version="1.0" encoding="UTF-8"?>
<dictionaries>
  <dictionary language="en-US">
    <translation key="legalMessage">[Legal]</translation>
  </dictionary>
  <dictionary language="sv-SE">
    <translation key="legalMessage">[Legal2]</translation>
  </dictionary>
</dictionaries>
```

This is how I am referencing that node. 

```
<LocalizableElement translationKey={'legalMessage'} parameters={params} />
```

Getting an error in the console without declaring the dictionary variable with empty language objects.
`localizablejs.js?7de5:117Uncaught TypeError: Cannot read property 'legalMessage' of undefined`

**Comment by WelcomWeb** [comment]
Hi @kriskhoury ! Thank you for you kind words.

You don't need to `init` LocalizableJs after using `read`, you just need to tell it to translate:

```
LocalizableJs.addChangeListener(type => {
    if (type === "dictionaries") {
        /* LocalizableJs initilized here */
        LocalizableJs.translateAll();
    }
});
LocalizableJs.read("translations/dictionaries.xml", "en-US");
```

You don't need to use `translateAll` if you're using the React bindings though, you can listen for a change on LocalizableJs with the type `dictionaries` and when it occurs you can re-render you component:

```
class MyComponent extends React.Component {
    state = { has_dictionaries: false };

    componentDidMount() {
        LocalizableJs.read("translations/dictionaries.xml", "en-US");
    }
    componentWillMount() {
        LocalizableJs.addChangeListener(this.onLocalizationChange);
    }
    componentWillUnmount() {
        LocalizableJs.removeChangeListener(this.onLocalizationChange);
    }

    onLocalizationChange = type => this.setState({ has_dictionaries: !this.state.has_dictionaries && type === "dictionaries" });

    render() {
        if (!this.state.has_dictionaries) {
            return <p>Loading...</p>;
        }

        return <LocalizableElement translationKey="legalMessage" parameters={params} />;
    }
}
```

**Comment by WelcomWeb** [comment]
I can also elaborate on why you are getting that error message: `read` makes an asynchronous request when fetching the XML file, meaning that the call to `init` is made _before_ the request is complete (and no dictionaries are loaded yet).

**Comment by kriskhoury** [comment]
@WelcomWeb, Thanks so much for the quick response. This worked!!

Cheers!!! 👍

**Comment by WelcomWeb** [comment]
Sorry, @kriskhoury - you can discard my comment about using `translateAll` instead of `init` - my code example suffers from the same problem as your provided example (using `init` too early, before the request is completed).

You're best off using the change listener even if you're not using the React bridge;

```
LocalizableJs.addChangeListener(type => {
    if (type === "dictionaries") {
        /* LocalizableJs initilized here */
        LocalizableJs.translateAll();
    }
});
LocalizableJs.read("translations/dictionaries.xml", "en-US");
```

This is somewhat clunky though, and I'll try to improve the usage when I have the time to update the code base.

**Comment by kriskhoury** [comment]
@WelcomWeb, thanks this worked for me. Although some of the LocalizableElement's were getting rendered before the xml loaded. So what I had to do was the following:

```
LocalizableJs.read('dictionaries.xml','en');
    LocalizableJs.addChangeListener(type => {
      if (type === "dictionaries") {
        LocalizableJs.translateAll();
        self.setState({
          localized: true
        });
      }
    }
});
```

The only additional thing I had to do was add a condition within the render. So that the page would only render when a `localized` variable was set. 

```
  render() {
    return (
      <div>
      { this.state.localized &&
            // stuff here
      }
    );
  }
}
```

Thanks alot!!!

PW: I tried adding a callback function to the `read` method which works also (reverting that in place of the above solution).
